import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { WalletContextProvider } from "@/hooks/useWallet";
import Provider from "@/hooks/provider";
import CommonClient from "./CommonClient";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};




export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <WalletContextProvider>
            <div className="bg-background text-slate-500">
              {children}
              <CommonClient />
            </div>
          </WalletContextProvider>
        </Provider>
      </body>
    </html>
  );
}
